### ISSUE TITLE
duration not picked up

### ISSUE THREAD

**Issue by kakulukia** [cristijora/vue2-transitions#7]
I have a list that has a basic slide-y-up-transition for adding and removing items which looks great, but as the list shall also be sortable, id like to disable the transition while sorting. 
I tried to use the duration but somehow its not working in my app tho its working in the demo app in the docs so i bet something is wrong with my code, but im currently blind. Please someone have a look:

    slide-y-up-transition(group, :duration="50")
        ListItem(:show="item", @itemDeleted="removeItem", :myList="myList",
                 v-for="(item, index) in list.items", :key="item.id", :index="index")

When removing the : from duration its correctly complaining about the being a string rather than a number, so ist reacting to the duration value in some way, but setting it to 0 still plays the transition.
What might be wrong here?

**Comment by cristijora** [comment]
Hi @kakulukia 
There is an issue with group transitions, because there is a `move` part to it. 
https://vuejs.org/v2/guide/transitions.html#List-Move-Transitions

As much as I would love to do that, the move (duration) part cannot be changed programmatically because Vue doesn't expose move js hooks like it does for enter/leave. 

So what this means is that you have to manually declare the move class. Vue 2 transitions has some default classes mentioned here 
https://github.com/cristijora/vue2-transitions#group-transitions

So besides `:duration="0"` you'd have to overwrite the css for that move class.
You could do it fairly simple like this
`<slide-y-up-transition group :class="{'no-move': yourDuration === 0}" :duration="yourDuration">

```
.no-move .slide-move{
  transition-duration: 0s;
}
```
So for duration 0, the move transition will be disabled, but for duration > 0, the move transition will be the default one from the readme. You could change that as well if you want

Here is an example https://codesandbox.io/s/kx718v7nk7

**Comment by kakulukia** [comment]
Thx for this qualified help! You should add that to the readme, i think.
Maybe my problem is more related to the sorting package im using .. im trying a different one ..
